analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - integration_test/**
  rules:
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - no-magic-number
    - avoid-unnecessary-setstate
    - avoid-missing-enum-constant-in-map
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - avoid-collection-methods-with-unrelated-types
    - avoid-global-state
    - avoid-unrelated-type-assertions
    - avoid-border-all
    - avoid-returning-widgets
    - prefer-const-border-radius
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
    - prefer-first
    - prefer-last
    - prefer-immediate-return
    - prefer-correct-type-name:
        min-length: 3
        max-length: 50
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - tag-name
    - always-remove-listener

  #    - prefer-correct-type-name
  #    - prefer-correct-identifier-length
  #    - avoid-wrapping-in-padding
  #    - prefer-extracting-callbacks
  #    - prefer-single-widget-per-file:
  #        ignore-private-widgets: true
  rules-exclude:
    - test/**
    - integration_test/**
    - test_driver/**
    - tools/**