name: atym_flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  dart_code_metrics: ^4.12.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  connectivity_plus: ^2.2.1
  cached_network_image: ^3.2.0
  get: ^4.6.1
  adaptive_action_sheet: ^2.0.1

  bloc_test: ^9.0.3
  network_image_mock: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
     - assets/mock_models/